require('dotenv').config();
const express = require('express');
const nodemailer = require('nodemailer');
const cors = require('cors');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static('./')); // Serve static files from the current directory

// Configure Nodemailer transporter
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
});

// Endpoint to handle new leads
app.post('/send-lead', async (req, res) => {
    try {
        const leadData = req.body;
        console.log('Received new lead:', leadData);

        // Format the email content
        let emailHtml = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 10px;">
                <h2 style="color: #004b8d; text-align: center; border-bottom: 2px solid #e31e24; padding-bottom: 10px;">New RVCN Lead Generated</h2>
                <div style="background-color: #f9f9f9; padding: 15px; border-radius: 8px; margin-top: 20px;">
                    <p><strong>Lead Type:</strong> <span style="color: #555;">${leadData.formType || 'General Inquiry'}</span></p>
                    <p><strong>Name:</strong> <span style="color: #555;">${leadData.name || 'Not provided'}</span></p>
                    <p><strong>Phone:</strong> <span style="color: #555;">${leadData.phone || 'Not provided'}</span></p>
        `;

        // Add dynamically collected extra fields
        if (leadData.email) emailHtml += `<p><strong>Email:</strong> <span style="color: #555;">${leadData.email}</span></p>`;
        if (leadData.city) emailHtml += `<p><strong>City:</strong> <span style="color: #555;">${leadData.city}</span></p>`;
        if (leadData.percentage) emailHtml += `<p><strong>12th Percentage:</strong> <span style="color: #555;">${leadData.percentage}%</span></p>`;
        if (leadData.specialization) emailHtml += `<p><strong>Specialization:</strong> <span style="color: #555;">${leadData.specialization}</span></p>`;
        if (leadData.programme) emailHtml += `<p><strong>Programme:</strong> <span style="color: #555;">${leadData.programme}</span></p>`;
        if (leadData.category) emailHtml += `<p><strong>Category:</strong> <span style="color: #555;">${leadData.category}</span></p>`;

        emailHtml += `
                </div>
                <p style="text-align: center; color: #888; font-size: 12px; margin-top: 30px;">This email was automatically generated by the RVCN Chatbot.</p>
            </div>
        `;

        const mailOptions = {
            from: `"RVCN Chatbot" <${process.env.EMAIL_USER}>`,
            to: process.env.RECEIVER_EMAIL,
            subject: `🚨 RVCN Chatbot: New Student Lead Submissions`,
            html: emailHtml
        };

        // Send the email
        await transporter.sendMail(mailOptions);
        console.log('Lead email sent successfully.');

        res.status(200).json({ success: true, message: 'Lead sent to email successfully.' });

    } catch (error) {
        console.error('Error sending lead email:', error);
        res.status(500).json({ success: false, message: 'Failed to send lead email.', error: error.message });
    }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`RVCN Backend Server running on http://localhost:${PORT}`);
});
